app:
  security:
    authentication: true
    jwt:
      algorithm: RSA
      public-key: MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAu5hQsHL/9qSq+mo8ayPZ6Z/sIZQfQvU0iLL2y/XMTAjjivDNKfjni/4cqjS1a1lk5gG0wnUsjY+prYJRHgcwBVk6BYdcfPggPLzcLM8Rg7W9tOTHP9jJ88rZcEvpYlbjNuE6eAtfYnZ1YFb+et3Bq05gzDsvpJUpubguw2rUPqvo65eA76BpMNyhFtrPmw09I4csLIbDqrtuagnV+GUNc1QCqTeM97G8tq35lquV/ZqzHRk272gk00QOtO6TmOR2lcMYK86aE9m89NgpkU9fttTa4i/oLJTuedLdR4fl6zmluPU9rqPekvR0kuKZw3aL5V5pRdz181PJ2NnXVL94KrLws9mWZ3n+uGwydOLnvJE9DOBXLGplj6N0ZP1rOyVSjz4yUP2aCBIMUzVaU2rFeLQ8BfETA0SOhKMa/Gqekk+Q6JuOi4sagJHORU/b/LH7iIf6Trggg9jwjeCxy8JV7WKUgrk0Y6UA2lHlckMM5oLujNs9QgWopEYDcGjDjLOM85kEhOuVMy5aPEvmt1zASMX+4lgdLgXb3zb8gwEaPXskwZHOR69EuhdwI3g/v+Xhy/S8Y2hqvzodsH7x89mt0pQQWcvdkgylDmQl0r1KUY5ZUEKRfctr+3TfyIJBVOC3BFcxVFUGzCW26mw5svvaxUr+m8QU1lSmutqQHOrITb8CAwEAAQ==
